services:
  products:
    user: "1000:1000"
    container_name: nestjs_products
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: nestdb
    depends_on:
      - postgres
    volumes:
      - ./products:/usr/src/products
      - /usr/src/products/node_modules
    command: npm run start:dev

  orders:
    container_name: nestjs_orders
    build:
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/nestdb
    depends_on:
      - postgres
    volumes:
      # Código fuente del host para desarrollo/hot reload
      - ./orders:/usr/src/orders

      # node_modules vive dentro de Docker,
      # no se sobrescribe con los archivos del host
      - orders_node_modules:/usr/src/orders/node_modules

  postgres:
    container_name: nestjs_postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client-gateway:
    container_name: nestjs_client_gateway
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      PORT: 3002
      PRODUCT_SERVICE_HOST: products
      PRODUCT_SERVICE_PORT: 3000
      ORDER_SERVICE_HOST: orders
      ORDER_SERVICE_PORT: 3001
      # DATABASE_HOST: postgres
      # DATABASE_PORT: 5432
      # DATABASE_USER: postgres
      # DATABASE_PASSWORD: postgres
      # DATABASE_NAME: nestdb
    depends_on:
      - products
    volumes:
      - ./client-gateway:/usr/src/gateway
      - gateway_node_modules:/usr/src/gateway/node_modules

    command: npm run start:dev

volumes:
  postgres_data:
  orders_node_modules:
  gateway_node_modules: