services:
  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: nestdb
    depends_on:
      - postgres
    volumes:
      - ./products:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    container_name: nestjs_postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client-gateway:
    container_name: nestjs_client_gateway
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      PORT: 3002
      # DATABASE_HOST: postgres
      # DATABASE_PORT: 5432
      # DATABASE_USER: postgres
      # DATABASE_PASSWORD: postgres
      # DATABASE_NAME: nestdb
    depends_on:
      - postgres
    volumes:
      - ./client-gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

volumes:
  postgres_data: